yml-vars:
  database:
    url: ${DATASOURCE_URL:postgresql://127.0.0.1:5432/mdm_files_db}
    username: postgres
    password: 123456

server:
  port: 8081
  error:
    include-message: always
    include-stacktrace: never

#logging:
#  level:
#    root: DEBUG

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.xml
    contexts: default
    url: jdbc:${yml-vars.database.url}
    user: ${yml-vars.database.username}
    password: ${yml-vars.database.password}
  r2dbc:
    url: r2dbc:${yml-vars.database.url}
    username: ${yml-vars.database.username}
    password: ${yml-vars.database.password}
  data:
    r2dbc:
      repositories:
        enabled: true